# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: distanceVec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='distanceVec.proto',
  package='distanceVector',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x64istanceVec.proto\x12\x0e\x64istanceVector\"%\n\tNeighbour\x12\n\n\x02ID\x18\x01 \x02(\t\x12\x0c\n\x04\x63ost\x18\x02 \x02(\x02\"G\n\x06Vector\x12\x0e\n\x06source\x18\x01 \x02(\t\x12-\n\nneighbours\x18\x02 \x03(\x0b\x32\x19.distanceVector.Neighbour')
)




_NEIGHBOUR = _descriptor.Descriptor(
  name='Neighbour',
  full_name='distanceVector.Neighbour',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='distanceVector.Neighbour.ID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='distanceVector.Neighbour.cost', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=74,
)


_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='distanceVector.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='distanceVector.Vector.source', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neighbours', full_name='distanceVector.Vector.neighbours', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=147,
)

_VECTOR.fields_by_name['neighbours'].message_type = _NEIGHBOUR
DESCRIPTOR.message_types_by_name['Neighbour'] = _NEIGHBOUR
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Neighbour = _reflection.GeneratedProtocolMessageType('Neighbour', (_message.Message,), dict(
  DESCRIPTOR = _NEIGHBOUR,
  __module__ = 'distanceVec_pb2'
  # @@protoc_insertion_point(class_scope:distanceVector.Neighbour)
  ))
_sym_db.RegisterMessage(Neighbour)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'distanceVec_pb2'
  # @@protoc_insertion_point(class_scope:distanceVector.Vector)
  ))
_sym_db.RegisterMessage(Vector)


# @@protoc_insertion_point(module_scope)
